[package]
name = "goban_screenhack"
version = "0.1.0"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2018"
default-run = "goban"

[[bin]]
name = "goban"
path = "src/main.rs"

[dependencies]
getopts = "~0.2"
glutin = "~0.24"
gl = "~0.14"
rand = "~0.7"
sgf-parse = "~0.2"

[dependencies.nanovg]
version = "1.0.2"
features = ["gl3"]
